Repository piskvorky/gensim, pull requests merged in 2018-03, with the labels that each got.

#1933 Refactor documentation for `gensim.models.coherencemodel`.
  gensim/models/coherencemodel.py
Labels: RFM, incubator project

#1780 Add Pivot Normalization for `gensim.models.TfidfModel`. Fix #220
  docs/notebooks/pivoted_document_length_normalisation.ipynb
  gensim/matutils.py
  gensim/models/tfidfmodel.py
  gensim/sklearn_api/tfidf.py
  gensim/test/test_tfidfmodel.py
Labels: incubator project

#1895 Fix docstrings for `gensim.sklearn_api`. Fix #1667
  gensim/sklearn_api/__init__.py
  gensim/sklearn_api/atmodel.py
  gensim/sklearn_api/d2vmodel.py
  gensim/sklearn_api/hdp.py
  gensim/sklearn_api/ldamodel.py
  gensim/sklearn_api/ldaseqmodel.py
  gensim/sklearn_api/lsimodel.py
  gensim/sklearn_api/phrases.py
  gensim/sklearn_api/rpmodel.py
  gensim/sklearn_api/text2bow.py
  gensim/sklearn_api/tfidf.py
  gensim/sklearn_api/w2vmodel.py
Labels: RFM, incubator project

#1954 Update rules for removing table markup. Fix #1710
  gensim/corpora/wikicorpus.py
  gensim/test/test_corpora.py
  gensim/test/test_data/enwiki-table-markup.xml.bz2
Labels: RFM
