Repository piskvorky/gensim, pull requests merged in 2019-01, with the labels that each got.

#2313 Fix critical issues in `FastText`
  docs/fasttext-notes.md
  gensim/models/_fasttext_bin.py
  gensim/models/_utils_any2vec.c
  gensim/models/_utils_any2vec.pyx
  gensim/models/fasttext.py
  gensim/models/keyedvectors.py
  gensim/models/utils_any2vec.py
  gensim/models/word2vec.py
  gensim/test/test_data/compatible-hash-false.model
  gensim/test/test_data/compatible-hash-true.model
  gensim/test/test_data/crime-and-punishment.bin
  gensim/test/test_data/crime-and-punishment.txt
  gensim/test/test_data/crime-and-punishment.vec
  gensim/test/test_data/toy-data.txt
  gensim/test/test_data/toy-model.bin
  gensim/test/test_data/toy-model.vec
  gensim/test/test_fasttext.py
  gensim/test/test_keyedvectors.py
  gensim/test/test_utils.py
Labels: 3.7.0

#2239 Fix overflow error for `*Vec` corpusfile-based training
  gensim/models/doc2vec_corpusfile.cpp
  gensim/models/doc2vec_corpusfile.pyx
  gensim/models/fasttext_corpusfile.cpp
  gensim/models/fasttext_corpusfile.pyx
  gensim/models/word2vec_corpusfile.cpp
  gensim/models/word2vec_corpusfile.pxd
  gensim/models/word2vec_corpusfile.pyx
Labels: bug, fasttext

#2007 Online NMF
  MANIFEST.in
  docs/notebooks/nmf_tutorial.ipynb
  docs/notebooks/nmf_wikipedia.ipynb
  docs/src/apiref.rst
  docs/src/models/nmf.rst
  gensim/models/nmf.py
  gensim/models/nmf_pgd.c
  gensim/models/nmf_pgd.pyx
  gensim/test/test_nmf.py
  setup.py
Labels: 3.7.0, incubator project, interesting PR :star:
