Repository piskvorky/gensim, pull requests merged in 2022-12, with the labels that each got.

#3406 Path Coherence Model to correctly handle empty documents
  gensim/test/test_coherencemodel.py
  gensim/topic_coherence/text_analysis.py
Labels: bug

#3381 clarify runtime expectations
  docs/src/auto_examples/tutorials/run_doc2vec_lee.ipynb
  docs/src/auto_examples/tutorials/run_doc2vec_lee.py
  docs/src/auto_examples/tutorials/run_doc2vec_lee.py.md5
  docs/src/auto_examples/tutorials/run_doc2vec_lee.rst
  docs/src/auto_examples/tutorials/sg_execution_times.rst
  docs/src/gallery/tutorials/run_doc2vec_lee.py
Labels: documentation

#3359 Fix bug that prevents loading old models
  gensim/models/word2vec.py
Labels: bug

#3410 refactor wheel building and testing workflow
  .github/workflows/build-wheels.yml
Labels: housekeeping

#3389 Fixed FastTextKeyedVectors handling in add_vector
  gensim/models/keyedvectors.py
  gensim/test/test_fasttext.py
Labels: bug
